### ISSUE TITLE
Service Manager Start Up Issue

### ISSUE THREAD

**Issue by AtesComp** [BeyondTrust/pbis-open#6]
The lwsmd.service file used to start the lwsmd service on boot does not always (rarely, if ever in my case) successfully contact the AD server on startup.  This is due to a race condition between the service starting and the network card becoming fully online.  The existing systemd service file is:

```
[Unit]
Description=BeyondTrust PBIS Service Manager
After=network.target 

[Service]
Type=forking
ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon 
ExecReload=/opt/pbis/bin/lwsm refresh
ExecStop=/opt/pbis/bin/lwsm shutdown
# We want systemd to give lwsmd some time to finish gracefully, but still want
# it to kill lwsmd after TimeoutStopSec if something went wrong during the
# graceful stop. Normally, Systemd sends SIGTERM signal right after the
# ExecStop, which would kill lwsmd. We are sending useless SIGCONT here to give
# lwsmd time to finish.
KillSignal=SIGCONT
PrivateTmp=false

[Install]
WantedBy=multi-user.target nss-lookup.target
```
A fix is to change the "After" line to read:

`After=network-online.target `

This forces the service to wait until the network service reports fully online.  As described at `https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/`, the `network.target` has little meaning.  The `network-online.target` is stronger relating to a NIC at least acquiring a route-able IP.

Even with the fix, occasionally the service will still fail probably due a lingering race condition between reporting online and actually being able to resolve network services.

**Comment by RBoulton-BT** [comment]
Thanks for this information, we'll investigate making this change.

In the most recent versions of PBIS-Open we added the option to domainjoin-cli to allow you to specify a --trustEnumerationWaitSeconds <timeout> when you do your join. This setting should retry the initial trust enumeration if it receives a failure and may improve your issue. 

I'd be interested to hear your feedback.

**Comment by AtesComp** [comment]
RBoulton-BT: From your comment, I understand that this `--trustEnumerationWaitSeconds` setting only applies to the `domainjoin-cli` program.  My issue occurs well after the machine has been successfully joined to the domain.

After rebooting, I cannot login as a domain user since some service started by the service manager did not enumerate/resolve the joined/default domain.  When logged in as a local user, a simple `enum-users` confirms the problem.  Restarting lwsmd, `sudo service lwsmd restart`, corrects the underlying problem.  At this point I usually restart my display manager, `sudo systemctl restart sddm.service`, so that my user list is updated/displayed and allows me to login as a domain user.

**Comment by RBoulton-BT** [comment]
domainjoin-cli is just the easiest way to set the timeout configuration. It's a per domain setting so our /opt/pbis/bin/config command isn't best suited to setting it.

The timeout is applied every time lwsmd(lsass) service restarts so we're hoping it may help out in these situations where lsass starts before networking is ready.

**Comment by AtesComp** [comment]
I see.  Where is that setting/value stored if not in the config/reg?

In any case, it seems that the `After=network-online.target` change should be applied as per the systemd documentation for this scenario.  This does fix the issue for a vast number of boots and does not require a custom fix in the PBIS code.

**Comment by RBoulton-BT** [comment]
Yes agreed, we'll definitely look to make this change to the lwsmd.service.

The TrustEnumerationWait settings are in the registry, the problem is the config tool can only update static locations. These values are under the domain you joined so it can't be used:

[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory\DomainJoin\<Your Domain>]
"TrustEnumerationWait"=dword:00000001
"TrustEnumerationWaitSeconds"=dword:0000003c

**Comment by AtesComp** [comment]
Thanks.  I did find them where you indicated.  I assume the regshell tool can manipulate them without issue.  I'll play around with the settings and do some reboots to test.

**Comment by AtesComp** [comment]
With `After=network-online.target`, I set the `TrustEnumerationWait` to 1 and `TrustEnumerationWaitSeconds` to 2.  So far I've only had one issue booting the computer--it did not list my users at the login screen.  When I checked the service, it was up and enumerated users without restarting the lsass service.  I restarted my display manager, SDDM, and all was good.  It was probably a timing issue between the DM starting and the wait.  I wonder if the DM service should wait on PBIS?  I've now set the `TrustEnumerationWaitSeconds` to 15 to test further.

**Comment by AtesComp** [comment]
On a cold boot, even setting the `TrustEnumerationWaitSeconds` to 15 resulted in my last post above.  The users enumerate so the service is properly running, but the DM did not list them in the login screen until I restarted the DM.  On a followup warm boot, all users displayed as expected.  If I were using a type-in username style login screen, I expect I would not even notice the problem.

**Comment by rbest-bt** [comment]
Can you provide some more information on your setup? Can you provide:
Distro
version
install setup - destop/minimal

**Comment by AtesComp** [comment]
Kubuntu 16.04.1 Desktop

**Comment by AtesComp** [comment]
I've tested by changing my SDDM login screen to a text entry username and password.  The `TrustEnumerationWaitSeconds` was left at 15.  This works without issue as I suspected.

I've now set the `TrustEnumerationWaitSeconds` to 1.  I'll test a few days and report later...

**Comment by Steffan-Ravn** [comment]
I would like to chime in with a me-to experience. 
We are using Ubuntu 16.04.1 Desktop with the latest PowerBroker and often see that the service is not online after a re-connect of the network cable. We have seen delays of up to 5 minutes before it successfully could resolve Active Directory requests again. If we restart the lwsmd service manually, everything returns to normal, queries again return the expected results from Active Directory etc.
I have tried with the mentioned fixes in this thread, but even though I've implemented both `After=network-online.target` and `--trustEnumerationWaitSeconds 5`, I still sometimes see that the lwsmd service fails to "recover" after a network disconnect.

**Comment by ovecka-m2** [comment]
Unfortunately, I must report the same problem. We're using dual-boot stations (W10&Mint18) joined to Zentyal 3.5 AD. Setting the `TrustEnumerationWaitSeconds` to any number between 2 and 15 and changing the `After=network-online.target` doesn't help. About half of our 16 computers are able to login after booting LM18 most of the time. Manually restarting the lwsmd service allows joining all the computers.

**Comment by AtesComp** [comment]
Well, it's been awhile, so I'm overdue for an update.
The 1 second setting was working well, then became a toss up, and now resulted in a recent string of fails.  Doing the manual restart of the service works, just annoying.  This last time I restarted the service, when logging in, it still failed.  I then did a "enum-users" and the user list was OK.  Then, log in worked.  It was odd that the service stared OK, but still failed at login.  Perhaps, there was some kind of delay with the service?  I always do:
```
sudo service lwsmd restart
sudo systemctl restart sddm.service
```

**Comment by rbest-bt** [comment]
We had have decided against After=network.target as it could cause issues in other areas in the product. We still have it in design to figure out a better solution.

We have found issues with some old gdm code that is outdated. We have plans to update this in the near future which should hopefully address the accounts populating.

Sorry to say these will not be in 8.5.3

**Comment by AtesComp** [comment]
I notice I never actually documented the error message, so here it is.  When doing:
`sudo systemctl status lwsmd.service`
in the output, I get:
> [lsass] Fatal error enumerating trusts for domain <xxx>. Error was ERROR_GEN_FAILURE (31)

**Comment by m0ps** [comment]
Also affected this issue on ubuntu 16.04 desktop

**Comment by sergeypugachov** [comment]
Also affected this issue on Linux Mint 17.3 abd 18.1.

It's look like issue is hardware dependent. I have five fresh and fast machines and there is no issue on it. Buto have encountered this bug on three older PCs...

**Comment by AtesComp** [comment]
I generally get this issue on cold boots.  It seemed to get worse for awhile.  Maybe a bad random streak.  The issue seems to be a race condition between the lwsmd service (or some related service) and the NIC (or other network services).

FYI: Technically, you don't "need" to restart the sddm.service (or other dm).  If I don't, my screen just looks a little funky when I switch back to the graphical console.

Even after restarting the lwsmd service to clear the error, I need to wait a bit before I can get a successful login--generally 30 to 60 seconds.

Anyway, I just updated to version 8.5.4.334 and will test.

**Comment by rbest-bt** [comment]
We've added a fix on August 4 that should address this. You can compile from source or wait until the end of the month when we'll have the beta packages ready.

There is still an issue with the AD accounts not showing up right away sometimes. After around 30 seconds they will. This was only showing up on lightDM (unity) not GDM (gnome).

**Comment by m0ps** [comment]
One small question... Where we can get beta packages?  Is there any beta repo (deb), or another place, where them published?

**Comment by rbest-bt** [comment]
When we have one, we'll tag it and post it on the [releases page](https://github.com/BeyondTrust/pbis-open/releases)

Current the [repos](http://repo.pbis.beyondtrust.com/) only host the latest release versions. It gets updated with official releases.

**Comment by AtesComp** [comment]
The same problem occurred with version 8.5.4.334.  I've reduced the command to reset down to just:
`sudo /opt/pbis/bin/lwsm restart netlogon`
This restarts reapsysl as well.  When restarting reapsysl alone, it has no effect.  So, I believe netlogon is the failing service (of course).

As for the update, I'll certainly test when it comes out.

FYI: I use SDDM & KDE.  I also use a typed in user name and password as opposed to listing all the users, so I don't think I'll have an issue with the AD accounts not showing up.

Question: Why doesn't the system use the cached credentials when it fails?

**Comment by RBoulton-BT** [comment]
The failure we've fixed relates to establishing the domain joined state for the agent. It was incorrectly treating an offline state as an error with our joined status. This is why pbis status was showing unknown. When we we do not believe we are joined to the domain, we cannot use the cache.

Hopefully this will be the same issue that you are seeing, although the issue we fixed was in lsass so I don't understand how restarting the netlogon service would have any effect.

**Comment by AtesComp** [comment]
My mistake.  When the "netlogon" service is restarted, it also restarts both "lsass" and "reapsysl".  The messages states something about "reverse dependencies".  Then, "lsass" may be the issue as stated.

Thanks for the clarification on the cached credentials.

**Comment by AtesComp** [comment]
Now, I've retested and reduced the command to reset down to just:
`sudo /opt/pbis/bin/lwsm restart lsass`
This works after the requisite 30-60 sec wait.  So, I think your fix will address this issue.

**Comment by rbest-bt** [comment]
Thank you for the confirmation.

**Comment by rbest-bt** [comment]
[8.5.5-beta.1 is up](https://github.com/BeyondTrust/pbis-open/releases/tag/8.5.5-beta.1). Includes fix:
77390 - Connection refused during startup causes PBIS join status Unknown

It would be great if you could try it out and let me know.

**Comment by ovecka-m2** [comment]
After some testing I'm glad to say the issue appears to be fixed. Tested on 10+ restarts on each of our 16 machines. No failure so far. Thank you.

**Comment by rbest-bt** [comment]
8.5.5.372 is up on the release page with the fix.
